### ISSUE TITLE
Column sizes in the url/command bar doesn't fill out correctly

### ISSUE THREAD

**Issue by DarkDefender** [qutebrowser/qutebrowser#3447]
After I did a system upgrade (including updating qutebrower), the url history and command suggestion dialog is unusable because the columns are too small:

![qute_bug](https://user-images.githubusercontent.com/312503/34418192-eb18bcd6-ebfc-11e7-8bbe-96c438d5673b.png)

I've tried to run quitebrowser with `--temp-basedir` and that didn't help so I'm guessing this is not configuration related.

```
zed@DarkRain ~ $ qutebrowser --version
[1228/182315.594991:WARNING:stack_trace_posix.cc(648)] Failed to open file: /tmp/#4194389 (deleted)
  Error: Filen eller katalogen finns inte
qutebrowser v1.0.4
Git commit: 2ef6e740d (2017-12-26 17:26:47 +0100)
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.5.4
Qt: 5.11.0
PyQt: 5.9.2

sip: 4.19.6
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 16.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.21.0
QtNetwork SSL: OpenSSL 1.0.2n  7 Dec 2017

Style: QFusionStyle
Platform: Linux-4.14.6-gentoo-x86_64-AMD_FX-tm-8120_Eight-Core_Processor-with-gentoo-2.4.1, 64bit
Linux distribution: Gentoo/Linux (gentoo)
Frozen: False
Imported from /usr/lib64/python3.5/site-packages/qutebrowser
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/zed/.cache/qutebrowser
config: /home/zed/.config/qutebrowser
data: /home/zed/.local/share/qutebrowser
runtime: /var/run/user/1000/qutebrowser

Uptime: 0:00:00
```

**Comment by The-Compiler** [comment]
Hm, that's odd. @rcorre do you have a clue what could be going on there?

**Comment by DarkDefender** [comment]
I should perhaps add. That it sometimes works as it should. But only after I've narrowed down the completions to a few. But this doesn't always work. So I'm not really sure why it resizes itself like this...

**Comment by rcorre** [comment]
Only thing I can think of is a change in qt 5.11, I'm still on 5.10. I'll see if I can repro with 5.11

**Comment by DarkDefender** [comment]
@rcorre Any luck reproducing this? I agree that this is probably a Qt bug, but I don't know the innerworkings of qutebrowser to figure out what changed.

**Comment by The-Compiler** [comment]
Seeing that Qt 5.11 isn't released yet: How did you install it, and what commit are you on exactly? Can you maybe try with Qt 5.10?

**Comment by mschilli87** [comment]
@The-Compiler: I didn't test it on my Gentoo box, but https://gitweb.gentoo.org/proj/qt.git/tree/dev-qt/qtcore/qtcore-5.9999.ebuild seems to be a live ebuild for testing qt that one could use via layman to get the latest (unreleased) Qt installed via Gentoo's `emerge`...

**Comment by DarkDefender** [comment]
@The-Compiler @mschilli87 yes I'm using the qt overlay to emerge the qt 9999 ebuild to get the latest git master version. (I needed to modify the qt overlay qt5.eclass though as some of the default flags in has been dropped/doesn't exist in qt 5.11)

It's been like this for about two weeks now. So I guess something changed around that time.
I can try with qt 5.10. But it will take a quite a few hours for me to downgrade. I can do it at a later date still if you want to.

**Comment by The-Compiler** [comment]
FWIW I won't have time to look into this in the next 4 weeks or so because of my exams. So feel free if you find the time :wink:

**Comment by DarkDefender** [comment]
I also have exams so I won't be able to look into this for a while either... :P

**Comment by DarkDefender** [comment]
Downgraded to qt 5.9 and now it works again. So this is probably an issue with newer qt versions.

**Comment by The-Compiler** [comment]
Any chance you can try with 5.10 as well?

**Comment by DarkDefender** [comment]
Sure I'll can do that in about two days. Just ping me if I haven't gotten back to you then.

**Comment by DarkDefender** [comment]
Doesn't seem to happen with 5.10 either. So I guess this is a 5.11 issue

**Comment by The-Compiler** [comment]
Thanks for checking! Can you please (with Qt 5.11) add this debug output:

```diff
diff --git a/qutebrowser/completion/completionwidget.py b/qutebrowser/completion/completionwidget.py
index 29f4f6653..3d2c7a861 100644
--- a/qutebrowser/completion/completionwidget.py
+++ b/qutebrowser/completion/completionwidget.py
@@ -153,6 +153,9 @@ class CompletionView(QTreeView):
         pixel_widths = [(width * perc // 100) for perc in column_widths]
 
         delta = self.verticalScrollBar().sizeHint().width()
+
+        print("total: {}, columns {}, pixel {}, delta {}".format(width, column_widths, pixel_widths, delta))
+
         if pixel_widths[-1] > delta:
             pixel_widths[-1] -= delta
         else:
```

and tell me what you get when opening the completion?

That should hopefully make it possible to narrow it down a bit. I'll try to get to the bottom of this before it's too late for a fix in 5.11.0, but I'm still busy with Qt 5.10 issues at the moment...

**Comment by DarkDefender** [comment]
I get this when I have the completion window open:
```
total: 1919, columns (40, 50, 10), pixel [767, 959, 191], delta 12
```
However, as I said previously, the results aren't always squished. But the output is still the same regardless if the results are messed up or not. So there doesn't seem to be correlated.

**Comment by The-Compiler** [comment]
That's weird. That means our calculation of the column widths is correct (I expected there to be an issue with that), but somehow setting them fails.

**Comment by The-Compiler** [comment]
Someone [reported something similar](https://www.riverbankcomputing.com/pipermail/pyqt/2018-February/040019.html) for Qt 5.9.4 on the PyQt mailinglist.

[QTBUG-66245](https://bugreports.qt.io/browse/QTBUG-66245) and [QTBUG-64578](https://bugreports.qt.io/browse/QTBUG-65478) might also be related in some way, though they speak about 5.9.4 and 5.10...

Though it might be possible that you were using a Qt 5.11 build after 5.10 was branched off, and before that fix was merged back to 5.11. Can you test with a more recent Qt 5.11 build by any chance?

**Comment by DarkDefender** [comment]
I'll try to build 5.11 sometime later this week. It takes around ~3h to compile everything so I'll do it when I have time.

**Comment by The-Compiler** [comment]
Sure, don't sweat it - as usual, I have enough other stuff to keep myself busy with :wink:

**Comment by DarkDefender** [comment]
Nope, 5.11 still has this issue.

**Comment by DarkDefender** [comment]
Ok, I just tried the new 5.11 alpha release and this issue is gone. (However I still can't load most sites as the render still crashes constantly)

Should I close this then?

**Comment by The-Compiler** [comment]
Yeah, I think it's fine to close this then, I don't think there's anything qutebrowser can do here. Can you show the output you get for the renderer crashes?

**Comment by DarkDefender** [comment]
The column issue seem to be fixed in 5.11 git master now also FYI.

I don't think that the render crashes are related to qutebrowser. This is the only relevant output I get from the crashes:
`[26555:26555:0223/200459.205948:FATAL:V8PerIsolateData.cpp(54)] Check failed: !ScriptForbiddenScope::IsScriptForbidden().`

**Comment by The-Compiler** [comment]
@DarkDefender FWIW I've seen the same issue and it's a Qt bug: [QTBUG-66338](https://bugreports.qt.io/browse/QTBUG-66338)
