### ISSUE TITLE
Rendering issues (grey boxes) on macOS 10.13.4 - webengine

### ISSUE THREAD

**Issue by tamasgal** [qutebrowser/qutebrowser#3967]
Good day,

I have some flickering when watching YouTube videos and some websites show semi transparent grey areas on the page (they are moving when scrolling), see the attached screenshot.

Is this a known issue? Unfortunately the grey boxes are only visible on our non-public jenkins server, but if I find another public website I'll report it here for the sake of reproducibility.

![screen shot 2018-05-31 at 23 52 54](https://user-images.githubusercontent.com/1730350/40810475-2cb038ea-652e-11e8-8752-10b78d0c984f.png)

**qute:version**
```
Version info

qutebrowser v1.3.1
Git commit: ac29c579f-dirty (2018-05-29 11:14:01 +0200)
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.5
Qt: 5.10.0
PyQt: 5.10

sip: 4.19.8
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.20.1
QtNetwork SSL: Secure Transport, macOS High Sierra (10.13)

Style: QWindowsStyle
Platform: Darwin-17.5.0-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.13.4, x86_64

Paths:
auto config: /Users/tamasgal/Library/Preferences/qutebrowser
cache: /Users/tamasgal/Library/Caches/qutebrowser
config: /Users/tamasgal/.qutebrowser
data: /Users/tamasgal/Library/Application Support/qutebrowser
runtime: /var/folders/n2/fpv312vd5xg91ncw_s5f1m5m0000gn/T/qutebrowser
```

**Comment by jgkamat** [comment]
This seems similar (maybe a duplicate) of #3901.

Maybe this will be fixed with a prebuilt image based on 5.11, it looked like a bug in qt.

**Comment by tamasgal** [comment]
Thanks for the quick reply!

I did `pip install PyQt5 qutebrowser` and then run `python -m qutebrowser`. I don't see any rendering issues on the Jenkins page anymore.
Also the binary which I installed from DMG is now rendering correctly.

So it was likely fixed by actually installing PyQt5 via pip.

Here is the `qute:version` output:

```
qutebrowser v1.3.1
Git commit: ac29c579f-dirty (2018-05-29 11:14:01 +0200)
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.5
Qt: 5.10.0
PyQt: 5.10

sip: 4.19.8
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.20.1
QtNetwork SSL: Secure Transport, macOS High Sierra (10.13)

Style: QWindowsStyle
Platform: Darwin-17.5.0-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.13.4, x86_64

Paths:
auto config: /Users/tamasgal/Library/Preferences/qutebrowser
cache: /Users/tamasgal/Library/Caches/qutebrowser
config: /Users/tamasgal/.qutebrowser
data: /Users/tamasgal/Library/Application Support/qutebrowser
runtime: /var/folders/n2/fpv312vd5xg91ncw_s5f1m5m0000gn/T/qutebrowser

Uptime: 0:01:54
```

**Comment by jgkamat** [comment]
The only difference between the previous reply is that you are using pyqt5 5.10.1, while the previous reply is using 5.10.0.

Maybe downgrading your pyqt version will help?

Im still not sure whats actually causing it (and I personally cant do any testing for it)

Also make sure to see the issue linked a couple comments above.

On June 6, 2018 10:24:59 AM EDT, Martin Schenck <notifications@github.com> wrote:
>That does not fix it for me.
>
>```
>Version info
>
>qutebrowser v1.3.1
>Git commit: 
>Backend: QtWebEngine (Chromium 61.0.3163.140)
>
>CPython: 3.6.5
>Qt: 5.10.1
>PyQt: 5.10.1
>
>sip: 4.19.8
>colorama: no
>pypeg2: 2.15
>jinja2: 2.10
>pygments: 2.2.0
>yaml: 3.12
>cssutils: no
>attr: 17.4.0
>PyQt5.QtWebEngineWidgets: yes
>PyQt5.QtWebKitWidgets: no
>pdf.js: no
>sqlite: 3.20.1
>QtNetwork SSL: Secure Transport, macOS High Sierra (10.13)
>
>Style: QMacStyle
>Platform: Darwin-17.5.0-x86_64-i386-64bit, 64bit
>Frozen: False
>Imported from /usr/local/lib/python3.6/site-packages/qutebrowser
>Qt library executable path:
>/usr/local/lib/python3.6/site-packages/PyQt5/Qt/libexec, data path:
>/usr/local/lib/python3.6/site-packages/PyQt5/Qt
>OS Version: 10.13.4, x86_64
>
>Paths:
>auto config: /Users/martin/Library/Preferences/qutebrowser
>cache: /Users/martin/Library/Caches/qutebrowser
>config: /Users/martin/.qutebrowser
>data: /Users/martin/Library/Application Support/qutebrowser
>runtime: /var/folders/t_/y2gwbym95ss72qjf6l4jr8f40000gn/T/qutebrowser
>
>Uptime: 0:00:17
>```

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by The-Compiler** [comment]
It's entirely possible that having Qt/PyQt installed globally (or not) makes some difference. It'd also explain why I never was able to reproduce this: I probably do have that installed on all my machines.

Still hope it'll get better with PyQt 5.11 (which will be released in a couple of days), reopening it for now.

**Comment by rien333** [comment]
Updating or installing anything didn't really do anything for me, even though all my version output is the same as @tamasgal's (or newer), which is kinda weird I guess. As I have accidentally completely replaced my qt installation from 5.10 to 5.11 I hope there will be a fix soon (or that PyQT 5.11 fixes it), because qutebrowser is now largely unusable for me.

**Comment by rien333** [comment]
Although the appropriate issue is probably more so #3901, given that the solution proposed in this thread did not help @schemar and me, I can confirm that installing the latest PyQt development build (i.e. PyQt5.11.dev1806121437)  fixed the rendering issue for me.

**Comment by reyesr** [comment]
Hi, not a user of qutebrowser, but I wanted to mention we had the same issue with Qt in our app (not a browser, but we instanciate the Qt WebEngine the same way). Investigating the issue with our customers, we recently pinpointed it happened only on macbook pros retina flagged as "Early 2015" by Apple (and only on this specific MBP with an Intel Iris 6100 graphics card).
The last Qt 5.11 release seems to fix the issue for our customers. I'll let you know if we gather more info.

**Comment by rien333** [comment]
I can confirm that I am an user of that exact macbook model.

**Comment by schemar** [comment]
I am on a 2018 MacBook Air

**Comment by The-Compiler** [comment]
Can you please try with the [v1.4.0 release](https://github.com/qutebrowser/qutebrowser/releases/tag/v1.4.0) which bundles Qt 5.11.1?

**Comment by schemar** [comment]
Fixed! 👍

**Comment by The-Compiler** [comment]
Awesome! :tada:

**Comment by tamasgal** [comment]
Nice 👍😎
