### ISSUE TITLE
qt5-webengine 5.12.3 -> 5.12.4 causes renderer to crash

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#4851]
**Version info (see `:version`)**: https://paste.the-compiler.org/view/ce468459

Reverting to 5.12.3 fixes the issue.

I forgot to try to test it with `--temp-basedir` before reverting to 5.12.3. I'll do it if that would help though.

**Comment by pyropeter** [comment]
I'm experiencing crashes with that release of `qt5-webengine`, too. I didn't test if downgrading helps. I can still open some websites (like https://www.kernel.org/) but not others (like https://github.com/qutebrowser/qutebrowser/issues).

I tried with `--temp-basedir`, though and found that it (apparently) completely fixes the problem. After that, I tried to delete my stored session with `:set auto_save.session false` and a restart, but that did not fix the problem. :man_shrugging:

**Comment by Eluminae** [comment]
Same prob. I got the feeling temp-basedir works. It not crash atm

**Comment by Eluminae** [comment]
I removed ~/.cache/qutebrowser and it do not crash anymore. Can other confirms ?

**Comment by jgkamat** [comment]
This is somehow fixed by clearing the cache directory.

See #4849 and http://bugreports.qt.io/browse/QTBUG-72532

**Comment by Penaz91** [comment]
I can confirm that removing ~/.cache/qutebrowser solves the render crashing.
Tested on Artix Linux, Qutebrowser 1.6.2, qt-webengine 5.12.4.

**Comment by prosoitos** [comment]
Ah great. It worked by only deleting `~/.cache/qutebrowser/webengine` the rest of the cache did not matter. Good news about #4849. Thanks!

**Comment by mrpewpew** [comment]
Deleting the cache worked for most websites but I still get a crash for https://web.whatsapp.com/

**Comment by The-Compiler** [comment]
Looks like this is [getting fixed](https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/265408) for Qt 5.12.5. I also added a [workaround](https://github.com/qutebrowser/qutebrowser/commit/67571d1ecee8ee70de20e90dc76f05d063ce485b) which removes `~/.cache/qutebrowser` on affected Qt upgrades and released v1.6.3 with it.

**Comment by aleprovencio** [comment]
I also still have problems with some sites, i.e. any links inside [https://g1.globo.com](https://g1.globo.com)

**Comment by mrjnox** [comment]
I'm able to consistently reproduce it at https://mail.google.com

```
10:01:15 DEBUG    commands   command:run:534 command called: open ['i']
10:01:15 DEBUG    commands   command:run:549 Calling qutebrowser.browser.commands.CommandDispatcher.openurl(<qutebrowser.browser.commands.CommandDispatcher>, 'i', False, False, False, False, None, False, False)
10:01:15 DEBUG    url        urlutils:get_path_if_valid:381 Checking if 'https://mail.google.com/' is a path
10:01:15 DEBUG    url        urlutils:fuzzy_url:214 URL is a fuzzy address
10:01:15 DEBUG    url        urlutils:fuzzy_url:217 Converting fuzzy term 'https://mail.google.com/' to URL -> https://mail.google.com/
10:01:15 DEBUG    webview    browsertab:_on_before_load_started:955 Going to start loading: https://mail.google.com/
10:01:15 DEBUG    webview    tabbedbrowser:on_title_changed:623 Changing title for idx 0 to 'https://mail.google.com/'
10:01:15 DEBUG    webview    browsertab:_on_before_load_started:955 Going to start loading: https://mail.google.com/
10:01:15 DEBUG    webview    tabbedbrowser:on_title_changed:623 Changing title for idx 0 to 'https://mail.google.com/'
10:01:15 DEBUG    mouse      mouse:eventFilter:55 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7fb11c565e58> got new child <PyQt5.QtWidgets.QWidget object at 0x7fb0fc4924c8>, installing filter
10:01:15 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_url_changed(PyQt5.QtCore.QUrl('https://mail.google.com/')) (tab 0)
10:01:15 DEBUG    modes      modeman:_handle_keypress:199 match: 2, forward_unbound_keys: auto, passthrough: True, is_non_alnum: True, dry_run: False --> filter: True (focused: <PyQt5.QtWidgets.QWidget object at 0x7fb11c516678>)
10:01:15 DEBUG    modes      modeman:_handle_keyrelease:219 filter: True
10:01:15 DEBUG    webview    browsertab:_set_load_status:921 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://mail.google.com/'>: LoadStatus.loading
10:01:15 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_status_changed(<LoadStatus.loading: 6>) (tab 0)
10:01:15 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_started() (tab 0)
10:01:15 DEBUG    modes      modeman:leave:307 Ignoring leave request for KeyMode.insert (reason load started) as we're in mode KeyMode.normal
10:01:15 DEBUG    modes      modeman:leave:307 Ignoring leave request for KeyMode.hint (reason load started) as we're in mode KeyMode.normal
10:01:15 DEBUG    webview    browsertab:_on_navigation_request:983 navigation request: url https://mail.google.com/, type Type.typed, is_main_frame True
10:01:15 DEBUG    webview    browsertab:_on_navigation_request:983 navigation request: url https://mail.google.com/mail/, type Type.typed, is_main_frame True
10:01:15 DEBUG    webview    browsertab:_on_navigation_request:983 navigation request: url https://mail.google.com/mail/u/0/, type Type.typed, is_main_frame True
10:01:15 DEBUG    mouse      mouse:eventFilter:79 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7fb11c565e58>: removed child <PyQt5.QtCore.QObject object at 0x7fb11c516828>
10:01:15 DEBUG    sql        sql:__init__:179 Preparing SQL query: "INSERT INTO History (url, title, atime, redirect) values(:url, :title, :atime, :redirect)"
10:01:15 DEBUG    sql        sql:run:212 Running SQL query: "INSERT INTO History (url, title, atime, redirect) values(:url, :title, :atime, :redirect)"
10:01:15 DEBUG    sql        sql:run:215 query bindings: {':atime': 1560870075, ':redirect': False, ':title': 'about:blank', ':url': 'https://mail.google.com/'}
10:01:15 DEBUG    sql        sql:__init__:179 Preparing SQL query: "REPLACE INTO CompletionHistory (url, title, last_atime) values(:url, :title, :last_atime)"
10:01:15 DEBUG    sql        sql:run:212 Running SQL query: "REPLACE INTO CompletionHistory (url, title, last_atime) values(:url, :title, :last_atime)"
10:01:15 DEBUG    sql        sql:run:215 query bindings: {':last_atime': 1560870075, ':title': 'about:blank', ':url': 'https://mail.google.com/'}
10:01:15 DEBUG    sessions   sessions:save:295 Saving session _autosave to /home/mrj/.local/share/qutebrowser/sessions/_autosave.yml...
10:01:15 DEBUG    webview    browsertab:_set_load_status:921 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://mail.google.com/'>: LoadStatus.success_https
10:01:15 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_status_changed(<LoadStatus.success_https: 3>) (tab 0)
10:01:15 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_finished(True) (tab 0)
10:01:15 DEBUG    sql        sql:__init__:179 Preparing SQL query: "INSERT INTO History (url, title, atime, redirect) values(:url, :title, :atime, :redirect)"
10:01:15 DEBUG    sql        sql:run:212 Running SQL query: "INSERT INTO History (url, title, atime, redirect) values(:url, :title, :atime, :redirect)"
10:01:15 DEBUG    sql        sql:run:215 query bindings: {':atime': 1560870075, ':redirect': False, ':title': 'about:blank', ':url': 'https://mail.google.com/'}
10:01:15 DEBUG    sql        sql:__init__:179 Preparing SQL query: "REPLACE INTO CompletionHistory (url, title, last_atime) values(:url, :title, :last_atime)"
10:01:15 DEBUG    sql        sql:run:212 Running SQL query: "REPLACE INTO CompletionHistory (url, title, last_atime) values(:url, :title, :last_atime)"
10:01:15 DEBUG    sql        sql:run:215 query bindings: {':last_atime': 1560870075, ':title': 'about:blank', ':url': 'https://mail.google.com/'}
10:01:15 DEBUG    sessions   sessions:save:295 Saving session _autosave to /home/mrj/.local/share/qutebrowser/sessions/_autosave.yml...
10:01:15 DEBUG    webview    browsertab:_set_load_status:921 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://mail.google.com/'>: LoadStatus.error
10:01:15 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_status_changed(<LoadStatus.error: 4>) (tab 0)
10:01:15 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_finished(False) (tab 0)
10:01:15 DEBUG    mouse      mouse:eventFilter:55 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7fb11c565e58> got new child <PyQt5.QtWidgets.QWidget object at 0x7fb11c516828>, installing filter
10:01:15 ERROR    webview    tabbedbrowser:show_error_page:811 Renderer process crashed
```
```
mrj@si:~_$ qutebrowser --version
qutebrowser v1.6.3
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.3
Qt: 5.12.4 (compiled 5.12.3)
PyQt: 5.12.2

sip: 4.19.17
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.28.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: QFusionStyle
Platform: Linux-5.1.9-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/mrj/.cache/qutebrowser
config: /home/mrj/.config/qutebrowser
data: /home/mrj/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:00
```

**Comment by brianbuccola** [comment]
I'm still getting the crash on certain sites (e.g. Twitter) even after nuking the cache.

**Comment by mrpewpew** [comment]
@brianbuccola [This other issue link](https://github.com/qutebrowser/qutebrowser/issues/4853) should fix your problem

**Comment by brianbuccola** [comment]
Thanks. Removing `~/.local/share/qutebrowser/webengine/Service\ Worker/ScriptCache` didn't work, but removing the entire `Service\ Worker` did.

**Comment by prosoitos** [comment]
I just submitted a crash report (I did not get the renderer crash message, this time qutebrowser had a fatal crash). I have not yet updated to `v1.6.3` though, so please ignore if that would fix it. Also, I have no idea whether the crash is linked with this since the behaviour is different.

**Comment by The-Compiler** [comment]
@prosoitos Unfortunately Qt 5.12.4 also has [a bug](https://bugreports.qt.io/browse/QTBUG-76440) which causes frequent crashes with High DPI scaling. There's a [fix](https://codereview.qt-project.org/c/qt/qtbase/+/265530) in review already and I'll try to ping the Arch maintainer to include it once it's reviewed.

**Comment by prosoitos** [comment]
Great! Thank you so much for all the work and for keeping up with the qt updates @The-Compiler. This is really much appreciated!
