### ISSUE TITLE
Qt 5.15: No screensaver/screen blanking inhibition when viewing videos?

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5504]
https://www.reddit.com/r/qutebrowser/comments/gumw2a/qutebrowser_v1120_released/ft28wqh

**Comment by The-Compiler** [comment]
Reproduced and reported upstream: [[QTBUG-85120] [REG 5.15] Screen blanking is not inhibited anymore - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-85120)

**Comment by The-Compiler** [comment]
FWIW on Archlinux, this is [fixed](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/qt5-webengine&id=fc7cbcf3af5fe895e7f19a2b8ce6333c150c362c) in qt5-webengine 5.15.0-3 which backports the upstream fix.

**Comment by wioo** [comment]
The problem is still present in 5.15.0-5 on archlinux.

**Comment by wioo** [comment]
Is it just me or is this still broken in 5.15.1?

**Comment by agarick** [comment]
Seems problematic for me too on voidlinux, [qutebrowser-1.13.1](https://github.com/void-linux/void-packages/tree/master/srcpkgs/qutebrowser), [qt5-webengine-5.15.1](https://github.com/void-linux/void-packages/tree/master/srcpkgs/qt5-webengine), [xorg-server-1.20.9](https://github.com/void-linux/void-packages/tree/master/srcpkgs/xorg-server).

How I've been seeing is:
1. `xset s 0 0 dpms 0 0 5`
1. Play a youtube video in a tab (fullscreen or otherwise)
1. 5 seconds later the screen blanks
    - where the desired behavior (I think) is to not blank until after the video is paused or the video-playing tab is closed

But I'm not sure if this is a sufficient reproduction of this issue. My setup has no power management or screensaving daemons running, nor a desktop environment like kde or gnome. The dbus daemon and openbox window manager are running, however. Also, mpv behaves as desired with this setup.

(By the way, I switched to qutebrowser a few days ago. It's so awesome; thank you.)

**Comment by The-Compiler** [comment]
Looks like there are more people having issues: [qutebrowser and idle display plyaing video : qutebrowser](https://www.reddit.com/r/qutebrowser/comments/j82a6r/qutebrowser_and_idle_display_plyaing_video/)

Reopening for now despite this not being a qutebrowser issue, as it should be reported upstream properly.

**Comment by basedtho** [comment]
any workaround?

**Comment by The-Compiler** [comment]
@basedtho [caffeine](https://launchpad.net/caffeine) (or [caffeine-ng](https://github.com/caffeine-ng/caffeine-ng)) probably

**Comment by blobject** [comment]
Thought I'd note that with a recent qutebrowser update on voidlinux, the issue has been fixed on my particular setup. Versions here are qutebrowser 2.0.1 and qt 5.15.2. (Actually the qt was updated earlier but I didn't think to test the inhibition behavior then, so I'm not sure which did the actual fixing.)

The following behavior is currently being seen on [sway](https://github.com/swaywm/sway) on wayland:
- Run the "screen blanking activator": `swayidle -w timeout 5 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"'`
- Play a youtube video on qutebrowser
- Make the application itself fullscreen (the video element inside the page need not be fullscreen -- it still works)
- dpms does not turn off in 5 seconds (yay)

**Comment by wioo** [comment]
Interesting. No change here (arch, X11).

**Comment by blobject** [comment]
Ah, my mistake. I forgot I had a sway config line: `for_window [app_id="qutebrowser"] inhibit_idle fullscreen` that was disabling blanking when fullscreen. Without it, the issue remains.

**Comment by Warepire** [comment]
I just realized I have this problem as well, and reading the Qt bugreport it seems that it should be finding and linking with libxss for X11 systems. At least on ArchLinux on X11 / AwesomeWM setup I cannot find a single trace of libXss being loaded by any QtWebEngineProcess instance.

`qt5-webengine 5.15.3-3`
`qutebrowser-git 2.1.0.r276.gfdc21e10d-1`

**Comment by laszloszurok** [comment]
Hey everyone!

This issue has annoyed me for a while, so I figured out a workaround for myself, until it gets fixed. 
I tought I'd share it, so others can use it too. It's a little shell script, that I wrote because I did not want to use caffeine. I wanted my system to automatically inhibit screen blanking when I watch a video in qutebrowser even if it's not in fullscreen. Maybe it's a little clunky, but works for my usecase.
The idea here is that I check if qutebrowser is playing sound, and if it is, DPMS and screensaver will be disabled, then reactivated, when there is no sound from qutebrowser anymore. On my system I use pulseaudio, so I check the sound with pacmd.

The script itself:
```
#!/bin/sh

while true; do
    dpms_state=$(xset q | grep "DPMS is")
    printf "%s\n" "$dpms_state"
    if pacmd list-sink-inputs | grep "qutebrowser" > /dev/null; then
        printf "Sound from qutebrowser detected\n"
        if [ "$dpms_state" = "  DPMS is Enabled" ]; then
            printf "Disabling screensaver and DPMS\n"
            xset s off
            xset -dpms
        fi
    else
        printf "No sound detected from qutebrowser\n"
        if [ "$dpms_state" = "  DPMS is Disabled" ]; then
            printf "Enabling screensaver and DPMS\n"
            xset s on
            xset +dpms
        fi
    fi
    printf "Gonna sleep now...\n"
    sleep 30
    printf "End of while loop\n\n"
done
```

Btw I have an other script which handles user inactivity, which contains the functionality of the above script and more:
https://github.com/laszloszurok/scripts/blob/master/utils/inactivity

**Comment by ArmouredHeart** [comment]
I'd like to report that I am also having this issue using qutebrowser v2.4.0 on Gentoo with default QtWebEngine compiled from source.

         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``
 
qutebrowser v2.4.0
Git commit:
Backend: QtWebEngine 5.15.2, based on Chromium 87.0.4280.144
Qt: 5.15.2
 
CPython: 3.9.9
PyQt: 5.15.4
 
sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.3
pygments: 2.10.0
yaml: 6.0
adblock: 0.5.1
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.35.5
QtNetwork SSL: OpenSSL 1.1.1l  24 Aug 2021
 
Style: Qt5CTProxyStyle
Platform plugin: xcb
OpenGL: Intel Open Source Technology Center, 2.1 Mesa 21.2.6
Platform: Linux-5.10.76-gentoo-r1-x86_64-x86_64-Intel-R-_Core-TM-2_Duo_CPU_P8600_@_2.40GHz-with-glibc2.33, 64bit
Linux distribution: Gentoo/Linux (gentoo)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3.9
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5

**Comment by The-Compiler** [comment]
As reported in #7041, this seems to be happening on Wayland too, which might or might not be the same underlying issue.

**Comment by frankplow** [comment]
Done a bit of research into this as it's been annoying me for a while. In my configuration, the issue resulted from using X screensaver extension (XSS) to manage display blanking and power management. This is what you get using `xset s`. QtWebEngine tries to use `org.*.ScreenSaver` dbus messages to inhibit blanking, which are not supported by XSS. I don't use Wayland so haven't looked into it so much, but I believe it is a similar story - neither want to have a dependence on dbus.

Not sure this could be fixed easily upstream, XSS doesn't provide a proper system for inhibiting blanking. They could implement a system similar to the [script laszloszurok posted above](https://github.com/qutebrowser/qutebrowser/issues/5504#issuecomment-932080700) to disable/enable XSS when going in/out of fullscreen, but this doesn't seem very robust and would not be trivial to implement.

Solutions include:
* [caffeine](https://launchpad.net/caffeine), which uses noop inputs to periodically reset the sleep timer. Other software which successfully inhibits blanking with XSS, such as VLC, takes this approach.
* Using other screensaver software such as gnome-screensaver. These support the dbus messages used by QtWebEngine to inhibit blanking. Most popular screensaver software supports these. xscreensaver seems to require [xscreensaver-systemd](https://man.archlinux.org/man/xscreensaver-systemd.6.en) to support this, but I've not tested.
* [xidlehook](https://github.com/jD91mZM2/xidlehook) can do checks for fullscreen or audio-playing applications before sending commands. It works similarly to xautolock or xss-lock.

At the moment I've taken the third approach, using xidlehook to launch xsecurelock. If anyone knows of a lightweight, DE-independent screensaver software which can be used with xsecurelock and which supports `org.FreeDesktop.ScreenSaver` dbus messages that would be much appreciated - I feel this is the most future-proof solution but all the examples I can find have lots of dependencies.

**Comment by The-Compiler** [comment]
@frankplow thanks, that's very useful information! Do you know whether Chromium correctly inhibits blanking in that case however?

**Comment by frankplow** [comment]
@The-Compiler no, chromium behaves just the same as qutebrowser and the Qt demo browser for me

**Comment by The-Compiler** [comment]
Hmm, yet [Unwanted Lock Screen : qutebrowser](https://www.reddit.com/r/qutebrowser/comments/ud2ijg/unwanted_lock_screen/) seem to suggest that people still have this issue with a variety of different screensavers/-lockers. Do they just all use XSS?

**Comment by Warepire** [comment]
As someone who doesn't use a DE, and no screensaver at all and just lets X put the monitors to sleep after inactivity instead, the drop of the X11 integration from chromium means that I am now required to either install a screensaver just so the chromium core works, or use another external tool to prevent my monitors being turned off when watching something online.

Can this loss of functionality qualify as a Qt bug?

**Comment by The-Compiler** [comment]
@Warepire doubt it, given that the functionality never was Qt functionality.

**Comment by frankplow** [comment]
@The-Compiler I think at a point in time it was, in the reponse to https://bugreports.qt.io/browse/QTBUG-85120 there is a reference to the XScreenSaver inhibition method being broken. I don't think it was ever fixed so [I've commented there](https://bugreports.qt.io/browse/QTBUG-85120?focusedCommentId=661397&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-661397) in an attempt to reopen that issue.

Wayland doesn't provide an equivalent to XSS, so more info is needed on anybody having issues under Wayland.

**Comment by wired** [comment]
I'm having the same issue, on Arch Linux w/ Wayland.
It's worth noting that Edge (in Wayland mode) works correctly on the same system.

**Comment by atreyasha** [comment]
Tried using `[xssproxy](https://github.com/vincentbernat/xssproxy)` as a workaround to forward dbus messages to XSS. Unfortunately, this did not solve the issue for me.
