### ISSUE TITLE
Pinch gesture on touchpad fails with multiple instances of QuteBrowser

### ISSUE THREAD

**Issue by SrShelo** [qutebrowser/qutebrowser#8671]
**Version info**:
qutebrowser v3.5.1
Git commit: 
Backend: QtWebEngine 6.9.1
  based on Chromium 130.0.6723.192
  with security patches up to 136.0.7103.114 (plus any distribution patches)
  (source: api)
Qt: 6.9.1

**Does the bug happen if you start with `--temp-basedir`?**:
No

When I have 2 instances of the qutebrowser open and perform the pinch gesture on the touchpad in both of the windows, the zoom only applies to one of them. It seems that the gesture from one window seems is "transfered" to the other, because I pinch in one window, but the zoom is applied to the other. 

**How to reproduce**
(By 'zoom' I mean 'zoom in' and 'zoom out'). Open qutebrowser and open 2 any sites in different tabs. Then execute ":tab-give" on one of the tabs and try to pinching on the touchpad in both windows. You can use this gesture to zoom in on one of the windows (A), and the same gesture on the other window will also zoom on window A.

**Comment by The-Compiler** [comment]
With "two instances", do you mean "two windows but in the same instance" (which is at least what your reproduction steps seem to hint at)?

Also, weird that you can't reproduce this with `--temp-basedir`. Are you trying the same steps you mentioned here? Can you show your `:config-diff`?

**Comment by SrShelo** [comment]
Wait, does 'two windows' not necessarily mean 'two instances'? My bad. And, due to my confusion regarding windows and instances is because I couldn't reproduce it with `--temp-basedir`; I executed the command `qutebrowser --temp-base-dir` in two terminals. My mistake again. I guess those two windows are really two instances. I'm correcting the post.

**Comment by SrShelo** [comment]
Sorry for my mistakes. I already corrected the post and title.

**Comment by ghost** [comment]
I've been having what I believe is the same issue. It seems to me that the last spawned window always takes the zoom, even if the window is not in focus. I can confirm at least for me, I still have this issue when running with and without the --temp-basdir flag. I have a video if this can help clarify;

https://www.youtube.com/watch?v=iY_qQGzHBGc

Edit; perhaps it's not the same issue, I didn't see the part about running :tab-give
Regardless if there's any information you need I can try to get it.
