### ISSUE TITLE
qt6-webengine 6.9.2-1 (Arch) breaks qutebrowser

### ISSUE THREAD

**Issue by mlmatlock** [qutebrowser/qutebrowser#8687]
**Version info**:
Unable to display version using qt6-webengine 6.9.2.

Version info (using qt6-ewbengine 6.9.1): https://bpa.st/YY5A

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**

New webengine version only displays a blank page, no matter what URL is input to open; see above: it won't even display the version info.

**How to reproduce**

Upgrade to qt6-webengine 6.9.2-1 (Arch). Start qutebrowser from the command-line:

```
INS  merell  ~  qutebrowser

12:43:52 INFO: Removing service workers at /home/merell/.local/share/qutebrowser/webengine/Service Worker (reason: QtWebEngine version changed)

12:43:52 WARNING: Backend texture is not a Vulkan texture.
```
Open any URL, and the above warning repeats until the page is loaded (apparently). Still blank page displayed.

Note: crossfiled to https://gitlab.archlinux.org/archlinux/packaging/packages/qt6-webengine/-/issues/9

**Comment by Chiitoo** [comment]
This came up on IRC a while ago, and so far seems to be an AMD + Wayland + Qt WebEngine issue (that is, not specific to qutebrowser).

Still an issue on Qt 6.10 (git master) too.

I don't think this [1] is in 6.9 yet, but running with

`QTWEBENGINE_CHROMIUM_FLAGS="--enable-features=Vulkan --use-vulkan=native --use-gl=stub"`

gets things going for me on Wayfire.

On 6.9 this should probably help to some extent at least:

`QT_QPA_PLATFORM="xcb"`

1. https://code.qt.io/cgit/qt/qtwebengine.git/commit/?h=6.10&id=bbaeadecfc455faf2e84cdf1b718bace73666828

**Comment by Chiitoo** [comment]
As an additional note, things also work for me if I downgrade from `mesa-git-master` to `mesa-25.1.8`, but this might be a different issue even if the symptoms are the same.

See also:

https://bugreports.qt.io/browse/QTBUG-139424

**Comment by The-Compiler** [comment]
Nothing actionable for qutebrowser here, this is a QtWebEngine issue. Pinning for visibility however.

**Comment by mlmatlock** [comment]
INFO: Fixed in Arch with qt6-webengine 6.9.2-2

**Comment by alscaldas** [comment]
Hi.

Qutebrowser has been constantly crashing. I noticed that it happens mostly when waking from suspension. The error message is the following:

```bash
[qua set 24 09:58:40 2025] traps: qutebrowser[158556] trap int3 ip:7f2836154361 sp:7ffd996efb98 error:0 in libQt6WebEngineCore.so.6.9.2[6154361,7f28300b9000+9fac000]
```

```bash
extra/qt6-webengine 6.9.2-2 (87.1 MiB 258.6 MiB) [qt6] (Instalado)
    Provides support for web applications using the Chromium browser project
```

Is this maybe related to that qt6-webengine issue? 

I'm asking because @mlmatlock mentioned that it was already fixed in this version 6.9.2-2. I already deleted the cache. Should I reinstall qutebrowser or something?

**Comment by The-Compiler** [comment]
That's unrelated. Sounds like [[QTBUG-136481] QtWebEngine crashes when screen is removed - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-136481), a [second fix](https://codereview.qt-project.org/c/qt/qtwebengine/+/644998) made it into Qt 6.9.2 but maybe it's still not fully/properly fixed.
